project_name: noah-mqtt
before:
  hooks:
    - go mod tidy
builds:
  - env:
    - CGO_ENABLED=0
    targets:
      - linux_arm_6
      - linux_arm64
      - linux_amd64_v1
      - darwin_amd64
      - darwin_arm64
      - windows_amd64
      - windows_arm64
    main: ./cmd/noah-mqtt
archives:
  - files:
    - LICENSE
    - passwd
checksum:
  name_template: 'checksums.txt'

dockers:
  - use: buildx
    goos: linux
    goarch: arm64
    build_flag_templates:
      - --platform=linux/arm64/v8
      - --label=org.opencontainers.image.title={{ .ProjectName }}
      - --label=org.opencontainers.image.description={{ .ProjectName }}
      - --label=org.opencontainers.image.url=https://github.com/mtrossbach/{{ .ProjectName }}
      - --label=org.opencontainers.image.source=https://github.com/mtrossbach/{{ .ProjectName }}
      - --label=org.opencontainers.image.version={{ .Version }}
      - --label=org.opencontainers.image.created={{ time "2006-01-02T15:04:05Z07:00" }}
      - --label=org.opencontainers.image.revision={{ .FullCommit }}
      - --label=org.opencontainers.image.licenses=Apache-2.0
    image_templates:
      - &arm64v8_image "ghcr.io/mtrossbach/{{ .ProjectName }}:{{ .Version }}-arm64v8"
    extra_files:
      - LICENSE
      - passwd
  - use: buildx
    goos: linux
    goarch: arm
    goarm: 6
    build_flag_templates:
      - --platform=linux/arm/v6
      - --label=org.opencontainers.image.title={{ .ProjectName }}
      - --label=org.opencontainers.image.description={{ .ProjectName }}
      - --label=org.opencontainers.image.url=https://github.com/mtrossbach/{{ .ProjectName }}
      - --label=org.opencontainers.image.source=https://github.com/mtrossbach/{{ .ProjectName }}
      - --label=org.opencontainers.image.version={{ .Version }}
      - --label=org.opencontainers.image.created={{ time "2006-01-02T15:04:05Z07:00" }}
      - --label=org.opencontainers.image.revision={{ .FullCommit }}
      - --label=org.opencontainers.image.licenses=Apache-2.0
    image_templates:
      - &armv6_image "ghcr.io/mtrossbach/{{ .ProjectName }}:{{ .Version }}-armv6"
    extra_files:
      - LICENSE
      - passwd
  - use: buildx
    goos: linux
    goarch: amd64
    build_flag_templates:
      - --platform=linux/amd64
      - --label=org.opencontainers.image.title={{ .ProjectName }}
      - --label=org.opencontainers.image.description={{ .ProjectName }}
      - --label=org.opencontainers.image.url=https://github.com/mtrossbach/{{ .ProjectName }}
      - --label=org.opencontainers.image.source=https://github.com/mtrossbach/{{ .ProjectName }}
      - --label=org.opencontainers.image.version={{ .Version }}
      - --label=org.opencontainers.image.created={{ time "2006-01-02T15:04:05Z07:00" }}
      - --label=org.opencontainers.image.revision={{ .FullCommit }}
      - --label=org.opencontainers.image.licenses=Apache-2.0
    image_templates:
      - &amd64_image "ghcr.io/mtrossbach/{{ .ProjectName }}:{{ .Version }}-amd64"
    extra_files:
      - LICENSE
      - passwd
      
docker_manifests:
  - name_template: "ghcr.io/mtrossbach/{{ .ProjectName }}:{{ .Version }}"
    image_templates:
      - *arm64v8_image
      - *armv6_image
      - *amd64_image
  - name_template: "ghcr.io/mtrossbach/{{ .ProjectName }}:latest"
    image_templates:
      - *arm64v8_image
      - *armv6_image
      - *amd64_image
    
release:
  github:
    owner: mtrossbach
    name: noah-mqtt
  draft: false
