FROM alpine AS builder

FROM scratch
COPY nexa-mqtt /
COPY LICENSE /
COPY passwd /etc/passwd
COPY --from=builder /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/
USER gouser
ENTRYPOINT ["/nexa-mqtt"]